export const mockUsers = [
  {
    id: "1",
    name: "Mark Bongalbal",
    role: "Developer",
    department: "Developer",
    email: "mark.bongalbal@company.com",
    phone: "(123) 456-7890",
    age: 22,
  },
  {
    id: "2",
    name: "Jan Emmanuel Cal",
    role: "Product Manager",
    department: "Product",
    email: "jan.emmanuel.cal@company.com",
    phone: "(555) 234-5678",
    age: 23,
  },
  {
    id: "3",
    name: "Shenna Mae Conde",
    role: "Paper Compiler",
    department: "Research",
    email: "shenna.mae.conde@company.com",
    phone: "(555) 345-6789",
    age: 20,
  },
  {
    id: "4",
    name: "Shiela Mae Fungo",
    role: "Paper Compiler",
    department: "Engineering",
    email: "shiela.mae.fungo@company.com",
    phone: "(555) 456-7890",
    age: 21,
  },
  {
    id: "5",
    name: "Kris Bon",
    role: "Video Editor",
    department: "Editorial",
    email: "kris.bon@company.com",
    phone: "(555) 567-8901",
    age: 23,
  },
  {
    id: "6",
    name: "David Kim",
    role: "Data Scientist",
    department: "Engineering",
    email: "david.kim@company.com",
    phone: "(555) 678-9012",
    age: 29,
  },
  {
    id: "7",
    name: "Celina Scott",
    role: "Paper Reviewer",
    department: "Checkers",
    email: "celina.scott@company.com",
    phone: "(555) 789-0123",
    age: 31,
  },
  {
    id: "8",
    name: "Alex Rodriguez",
    role: "Junior Developer",
    department: "Engineering",
    email: "alex.rodriguez@company.com",
    phone: "(555) 890-1234",
    age: 24,
  },
  {
    id: "9",
    name: "Jessica Lee",
    role: "Content Manager",
    department: "Marketing",
    email: "jessica.lee@company.com",
    phone: "(555) 901-2345",
    age: 28,
  },
  {
    id: "10",
    name: "Robert Brown",
    role: "Finance Analyst",
    department: "Finance",
    email: "robert.brown@company.com",
    phone: "(555) 012-3456",
    age: 33,
  },
  {
    id: "11",
    name: "Angela White",
    role: "DevOps Engineer",
    department: "Engineering",
    email: "angela.white@company.com",
    phone: "(555) 111-2222",
    age: 29,
  },
  {
    id: "12",
    name: "Christopher Bell",
    role: "Sales Representative",
    department: "Sales",
    email: "christopher.bell@company.com",
    phone: "(555) 222-3333",
    age: 26,
  },
]
