export const mockUsers = [
  {
    id: "1",
    name: "Sarah Johnson",
    role: "Senior Software Engineer",
    department: "Engineering",
    email: "sarah.johnson@company.com",
    phone: "(555) 123-4567",
    age: 28,
  },
  {
    id: "2",
    name: "Michael Chen",
    role: "Product Manager",
    department: "Product",
    email: "michael.chen@company.com",
    phone: "(555) 234-5678",
    age: 32,
  },
  {
    id: "3",
    name: "Emma Davis",
    role: "UX Designer",
    department: "Design",
    email: "emma.davis@company.com",
    phone: "(555) 345-6789",
    age: 26,
  },
  {
    id: "4",
    name: "James Wilson",
    role: "Backend Engineer",
    department: "Engineering",
    email: "james.wilson@company.com",
    phone: "(555) 456-7890",
    age: 30,
  },
  {
    id: "5",
    name: "Lisa Martinez",
    role: "Marketing Specialist",
    department: "Marketing",
    email: "lisa.martinez@company.com",
    phone: "(555) 567-8901",
    age: 27,
  },
  {
    id: "6",
    name: "David Kim",
    role: "Data Scientist",
    department: "Engineering",
    email: "david.kim@company.com",
    phone: "(555) 678-9012",
    age: 29,
  },
  {
    id: "7",
    name: "Rachel Thompson",
    role: "HR Manager",
    department: "Human Resources",
    email: "rachel.thompson@company.com",
    phone: "(555) 789-0123",
    age: 31,
  },
  {
    id: "8",
    name: "Alex Rodriguez",
    role: "Junior Developer",
    department: "Engineering",
    email: "alex.rodriguez@company.com",
    phone: "(555) 890-1234",
    age: 24,
  },
  {
    id: "9",
    name: "Jessica Lee",
    role: "Content Manager",
    department: "Marketing",
    email: "jessica.lee@company.com",
    phone: "(555) 901-2345",
    age: 28,
  },
  {
    id: "10",
    name: "Robert Brown",
    role: "Finance Analyst",
    department: "Finance",
    email: "robert.brown@company.com",
    phone: "(555) 012-3456",
    age: 33,
  },
  {
    id: "11",
    name: "Angela White",
    role: "DevOps Engineer",
    department: "Engineering",
    email: "angela.white@company.com",
    phone: "(555) 111-2222",
    age: 29,
  },
  {
    id: "12",
    name: "Christopher Bell",
    role: "Sales Representative",
    department: "Sales",
    email: "christopher.bell@company.com",
    phone: "(555) 222-3333",
    age: 26,
  },
]
